---
- hosts: swarm_manager
  become: yes

  vars:
    docker_host: "unix:///var/run/docker.sock"

  vars_files:
    - env.yml

  pre_tasks:
    - name: Update APT package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker Collection (community.docker)
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.docker --force

    - name: Make sure the python3-apt package is installed
      ansible.builtin.apt:
        name: python3-apt
        state: present

    - name: Make sure the python3-venv package is installed
      ansible.builtin.apt:
        name: python3-venv
        state: present

    - name: Make sure the python3-pip package is installed
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Install Python packages (jsondiff, requests, docker, urllib3, chardet)
      ansible.builtin.pip:
        name:
          - jsondiff
          - requests>=2.25.1
          - docker
          - urllib3>=1.26.5
          - chardet>=3.0.4
        state: present

    - name: Uninstall Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: absent
        purge: yes

    - name: Remove Docker's storage directories
      ansible.builtin.command:
        cmd: rm -rf /var/lib/docker /var/lib/containerd
        warn: false

    - name: Install dependencies for Docker
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Create the /etc/apt/keyrings directory (if necessary)
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key to /etc/apt/keyrings
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository manually
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
        filename: docker.list
        update_cache: yes
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is started and enabled
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Set environment variable for Docker Host
      ansible.builtin.set_fact:
        DOCKER_HOST: "{{ docker_host }}"

    - name: Add active user to the docker group
      ansible.builtin.shell: "usermod -aG docker $USER"

    - name: Log in to Azure Container Registry
      community.docker.docker_login:
        registry_url: "{{ DOCKER_REGISTRY_URL }}"
        username: "{{ DOCKER_REGISTRY_USER }}"
        password: "{{ DOCKER_REGISTRY_PASSWORD }}"

    - name: Verify Docker login
      command: docker info

    - name: Initialize Docker Swarm
      community.docker.docker_swarm:
        state: present
        advertise_addr: "{{ HOST_IP }}"

    - name: Create Docker Secrets
      include_tasks: stacks/esm2/secrets/create_secrets.yml

    - name: Create Prometheus data volume
      community.docker.docker_volume:
        name: prometheus_data
        state: present

    - name: Create Grafana storage volume
      community.docker.docker_volume:
        name: grafana_storage
        state: present

    - name: Create Portainer data volume
      community.docker.docker_volume:
        name: portainer_data
        state: present

    - name: Create Docker network for sm_network (if not exists)
      community.docker.docker_network:
        name: sm_network
        state: present
        driver: overlay
        scope: swarm

    #    - name: Create Docker network for monitoring_network (if not exists)
    #      community.docker.docker_network:
    #        name: monitoring_network
    #        driver: overlay
    #        state: present
    #        attachable: yes
    #        scope: swarm

  tasks:
    - name: Generate backend Docker Swarm file (esm2)
      template:
        src: stacks/esm2/backend/docker-swarm.yml.j2
        dest: stacks/esm2/backend/docker-swarm.yml

    - name: Generate frontend Docker Swarm file (esm2)
      template:
        src: stacks/esm2/frontend/docker-swarm.yml.j2
        dest: stacks/esm2/frontend/docker-swarm.yml

    - name: Generate Prometheus configuration file
      template:
        src: stacks/esm2/logging/prometheus/prometheus.yml.j2
        dest: stacks/esm2/logging/prometheus/prometheus.yml

    - name: Generate Grafana datasources configuration file
      template:
        src: stacks/esm2/logging/grafana/datasources.yml.j2
        dest: stacks/esm2/logging/grafana/datasources.yml

    - name: Create certs directory
      ansible.builtin.file:
        path: ./stacks/esm2/backend/certs
        state: directory
        mode: '0755'

    - name: Create storage directory
      ansible.builtin.file:
        path: ./stacks/esm2/backend/storage
        state: directory
        mode: '0755'

    - name: Deploy the backend stack (esm2)
      community.docker.docker_stack:
        name: esm2
        state: present
        with_registry_auth: yes
        compose:
          - stacks/esm2/backend/docker-swarm.yml

    - name: Deploy the frontend stack (esm2)
      community.docker.docker_stack:
        name: esm2
        state: present
        with_registry_auth: yes
        compose:
          - stacks/esm2/frontend/docker-swarm.yml

    - name: Deploy the logging stack (monitoring)
      community.docker.docker_stack:
        name: monitoring
        state: present
        compose:
          - stacks/esm2/logging/docker-swarm.yml

    - name: Verify that the esm2 stack is running
      command: docker stack ps esm2
      register: esm2_result
      changed_when: false

    - name: Verify that the monitoring stack is running
      command: docker stack ps monitoring
      register: monitoring_result
      changed_when: false

    - name: Show esm2 stack services status
      debug:
        var: esm2_result.stdout_lines

    - name: Show monitoring stack services status
      debug:
        var: monitoring_result.stdout_lines