global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]
    basic_auth:
      username: 'admin'
      password: 'k7zCRa7vrXOTF8mGRoVbG8tn'

  - job_name: 'cadvisor'
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'A'
        port: 8080

  - job_name: 'node_exporter'
    dns_sd_configs:
      - names:
          - 'tasks.node_exporter'
        type: 'A'
        port: 9100

  - job_name: 'api-health-check'
    metrics_path: '/probe'
    params:
      module: [ http_2xx ]
    scrape_interval: 5s
    static_configs:
      - targets: [ '10.105.0.4:8085/api/v1/health-check' ]
    relabel_configs:
      - source_labels: [ _address_ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: _address_
        replacement: blackbox_exporter:9115