apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://10.105.0.4:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://10.105.0.4:3100