services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
    ports:
      - "5432:5432"
    secrets:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    networks:
      - sm_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: '$DOCKER_REGISTRY_URL/${BACK_IMAGE_NAME}:${TAG_NAME}'
    environment:
      ENABLE_SSL: ${ENABLE_SSL}
      KEY_STORE_LOCATION: ${KEY_STORE_LOCATION}
      KEY_STORE_PASSWORD: ${KEY_STORE_PASSWORD}
      UPLOAD_BASEPATH: ${UPLOAD_BASEPATH}
      UPLOAD_BASEURI: ${UPLOAD_BASEURI}
      FHIR_AUTH_URL_FILE: ${FHIR_AUTH_URL}
      FHIR_URL: ${FHIR_URL}
      FHIR_INTEGRATION_USER_FILE: /run/secrets/FHIR_INTEGRATION_USER
      DB_USER_FILE: /run/secrets/DB_USER
      DB_PASSWORD_FILE: /run/secrets/DB_PASSWORD
      DB_ESM_FILE: /run/secrets/DB_ESM
    ports:
      - "8080:8080"
      - "8443:8443"
    secrets:
      - FHIR_INTEGRATION_USER
      - DB_USER
      - DB_PASSWORD
      - DB_ESM
    volumes:
      - ./certs:/app/keystore
      - ./storage:/app/storage
    networks:
      - sm_network
    depends_on:
      - postgres
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
      rollback_config:
        parallelism: 1
        delay: 10s
        monitor: 60s
    healthcheck:
      test: [ "CMD", "curl", "--insecure", "--fail", "--location", "https://localhost:8443/api/v1/health-check" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  sm_network:
    external: true

volumes:
  postgres_storage:
    driver: local

secrets:
  POSTGRES_DB:
    external: true
  POSTGRES_PASSWORD:
    external: true
  POSTGRES_USER:
    external: true
  FHIR_INTEGRATION_USER:
    external: true
  DB_ESM:
    external: true
  DB_USER:
    external: true
  DB_PASSWORD:
    external: true